"""
Core audit events table — the single source of truth for every recorded
agent action.

Schema per architecture-v1.md §2.3.
"""

import uuid
from datetime import UTC, datetime

from sqlalchemy import (
    BigInteger,
    Boolean,
    DateTime,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    text,
)
from sqlalchemy.dialects.postgresql import INET, JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from .base import Base


class Event(Base):
    __tablename__ = "events"

    # ── Primary key ──────────────────────────────────────────
    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)

    # ── Event identity ───────────────────────────────────────
    event_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),
        nullable=False,
    )
    session_id: Mapped[str] = mapped_column(String, nullable=False)
    sequence: Mapped[int] = mapped_column(
        Integer, default=0, server_default=text("0"), nullable=False
    )
    timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(UTC),
        server_default=text("now()"),
        nullable=False,
    )

    # ── Audit dimensions ─────────────────────────────────────
    event_type: Mapped[str] = mapped_column(
        String, nullable=False
    )  # decision|tool_call|model_request|guardrail|error
    agent_id: Mapped[str] = mapped_column(String, nullable=False)
    prompt_version: Mapped[str] = mapped_column(
        String, default="", server_default=text("''"), nullable=False
    )

    # ── Content ──────────────────────────────────────────────
    input_snapshot: Mapped[str] = mapped_column(Text, default="", server_default=text("''"))
    output_snapshot: Mapped[str] = mapped_column(Text, default="", server_default=text("''"))
    metadata_: Mapped[dict] = mapped_column(
        "metadata", JSONB, default=dict, server_default=text("'{}'")
    )

    # ── Hash chain (tamper-evident core) ─────────────────────
    prev_hash: Mapped[str] = mapped_column(
        String, default="", server_default=text("''"), nullable=False
    )
    hash: Mapped[str] = mapped_column(String, default="", server_default=text("''"), nullable=False)

    # ── Ed25519 signature (optional) ─────────────────────────
    signature: Mapped[str] = mapped_column(String, default="", server_default=text("''"))
    sign_key_id: Mapped[str] = mapped_column(String, default="", server_default=text("''"))

    # ── LLM trace (v1.0 OpenTelemetry integration) ───────────
    trace_id: Mapped[str] = mapped_column(String, default="", server_default=text("''"))
    span_id: Mapped[str] = mapped_column(String, default="", server_default=text("''"))
    parent_span_id: Mapped[str] = mapped_column(String, default="", server_default=text("''"))

    # ── Audit metadata ───────────────────────────────────────
    pii_redacted: Mapped[bool] = mapped_column(Boolean, default=False, server_default=text("FALSE"))
    source_ip: Mapped[str | None] = mapped_column(INET)  # PostgreSQL INET type
    user_agent: Mapped[str] = mapped_column(String, default="", server_default=text("''"))

    # ── Constraints ──────────────────────────────────────────
    __table_args__ = (
        UniqueConstraint("event_id", name="uq_events_event_id"),
        UniqueConstraint("session_id", "sequence", name="uq_events_session_sequence"),
        # Indexes — named explicitly for clarity; naming_convention in
        # base.py also applies as a fallback for autogenerated names.
        Index("ix_events_ts", timestamp.desc()),
        Index("ix_events_session", "session_id", "sequence"),
        Index("ix_events_agent", "agent_id", timestamp.desc()),
        Index("ix_events_type", "event_type", timestamp.desc()),
        Index("ix_events_trace", "trace_id"),
        Index("ix_events_metadata", "metadata", postgresql_using="GIN"),
    )

    def __repr__(self) -> str:
        return (
            f"<Event(id={self.id} event_id={self.event_id} "
            f"session={self.session_id} seq={self.sequence} "
            f"type={self.event_type})>"
        )
