{{- if .Values.nginx.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agent-audit.fullname" . }}-nginx
  labels:
    app.kubernetes.io/component: nginx
    {{- include "agent-audit.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  strategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  selector:
    matchLabels:
      app.kubernetes.io/component: nginx
      {{- include "agent-audit.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/nginx-conf: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/component: nginx
        {{- include "agent-audit.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: nginx
          image: {{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.nginx.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.nginx.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
              readOnly: true
      volumes:
        - name: nginx-conf
          configMap:
            name: {{ include "agent-audit.fullname" . }}-nginx-conf
{{- end }}
