apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent-audit.fullname" . }}-api
  labels:
    app.kubernetes.io/component: api
    {{- include "agent-audit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.serviceType }}
  ports:
    - port: {{ .Values.api.servicePort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: api
    {{- include "agent-audit.selectorLabels" . | nindent 4 }}
